version: 2.1
orbs:
  golang: circleci/go@1.6.0
  heroku: circleci/heroku@1.2.6
jobs:
  build:
    executor: go/default
    steps:
      - checkout
      - run:
          name: Setup Env
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=golang-checkip' >> $BASH_ENV
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            docker build -t adityacprtm/$IMAGE_NAME:$TAG .
            docker images
            docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
            docker push adityacprtm/$IMAGE_NAME:$TAG
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - run:
          name: Storing previous commit
          command: |
            git rev-parse HEAD > ./commit.txt
      - heroku/install
      - setup_remote_docker
      - run:
          name: Pushing to heroku registry
          command: |
            heroku container:login
            heroku container:push web -a $HEROKU_APP_NAME
            heroku container:release web -a $HEROKU_APP_NAME
workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
